language: node_js

node_js:
  - "14"

os:
  - linux

dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid-fallback

install:
  - npm install codecov -g

before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor

script:
  - ./flutter/bin/flutter test

cache:
  directories:
    - $HOME/.pub-cache

after_success:
  - codecov -f ./coverage/lcov.info
