name: tanyao
description: "Tan'yao-chuu! 1000 points!"

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.1
  logger: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
